# docker-compose.yml
version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - /etc/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "healthchecker", "-h", "localhost"]
      interval: 2s
      timeout: 2s
      retries: 10
