# docker-compose.yml
version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
      - /etc/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "healthchecker", "-d", "gova11y", "-h", "localhost"]
      interval: 2s
      timeout: 2s
      retries: 10
  postgres1:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        POSTGRES_USER:
        POSTGRES_PASSWORD:
      ports:
        - "5433:5432"
      volumes:
        - /var/lib/postgresql/data
        - /etc/postgresql
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "healthchecker", "-d", "gova11y", "-h", "localhost"]
        interval: 2s
        timeout: 2s
        retries: 10

