# docker-compose.yml

version: "3"
services:
    server:
      image: postgrest/postgrest
      hostname: postgrest
      ports:
          - "3000:3000"
      environment:
          PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
          PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      depends_on:
          - postgres
      deploy:
        restart_policy:
          condition: always
          delay: 10s
          max_attempts: 5
          window: 120s
      networks:
        - postgres
        - gova11y

    postgres:
      image: gova11y/postgres:latest
      ports:
          - "5432:5432"
      environment:
        POSTGRES_DB: app_db
        POSTGRES_USER: app_user
        POSTGRES_PASSWORD: password
      deploy:
        restart_policy:
          condition: always
          delay: 10s
          max_attempts: 5
          window: 120s
      networks:
        - postgres

    swagger:
      image: swaggerapi/swagger-ui
      ports:
        - "8080:8080"
  #    expose:
        - "8080"
 #       environment:
   #         API_URL: http://localhost:3000/
    # Uncomment this if you want to persist the data.
    # volumes:
    #   - "./pgdata:/var/lib/postgresql/data"
